import Koa from 'koa'
import bodyParser from 'koa-bodyparser'
import Router from '@koa/router'
import { koaSwagger } from 'koa2-swagger-ui'

// These are generated by `npx tsoa spec-and-routes`
import swagger from './build/swagger.json'
import { RegisterRoutes } from './build/routes'

const app = new Koa()
const router = new Router()

app.use(bodyParser())

// Register tsoa-generated routes
RegisterRoutes(router)
app.use(router.routes())
app.use(router.allowedMethods())

// Swagger UI
app.use(
  koaSwagger({
    routePrefix: '/docs',
    exposeSpec: true,
 swaggerOptions: {
  spec: swagger
}

  })
)

app.listen(3000, () => {
  console.log('Server running at http://localhost:3000')
  console.log('Swagger UI available at http://localhost:3000/docs')
})