###
GET http://localhost:3000/books

###
GET http://localhost:3000/books?filters[0][from]=20&filters[0][to]=40

###
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "McMasterful Book",
  "author": "Emily",
  "description": "A guide to frontend/backend harmony",
  "price": 19.99,
  "image": "https://example.com/mcmasterful.jpg"
}
###
PUT http://localhost:3000/books/6974ebcb8f0104e9556eba86
Content-Type: application/json

{
  "title": "Updated Book Title",
  "author": "Emily E",
  "year": 2026
}

###
DELETE  http://localhost:3000/books/6974ebcb8f0104e9556eba86
